# Generated by Django 4.2.1 on 2023-06-23 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dishsearchapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="dish",
            table="dishsearchapp_dish",
        ),
    ]
